name: Test_Html_file
on:
    push:
        branches: [main]

jobs:
  run-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3

      - name: Start a simple HTTP server
        run: python3 -m http.server 8000 &
        
      - name: Wait and check if the server is running
        run: curl -I http://localhost:8000
