name: Test_HTML_File
on:
  push:
    branches: [main]

jobs:
  check-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files to verify HTML exists
        run: ls -l

      - name: Validate HTML file
        run: cat index.html  # Replace with your HTML file name
